import streamlit as st
from app_core import answer_question

# ======================================================
# PAGE CONFIG
# ======================================================
st.set_page_config(
    page_title="Enterprise Policy RAG Assistant",
    page_icon="📘",
    layout="wide"
)

# ======================================================
# HEADER
# ======================================================
st.markdown(
    """
    <h1 style='text-align:center;'>📘 Enterprise Policy RAG Assistant</h1>
    <p style='text-align:center; color:gray; font-size:16px;'>
    An explainable, enterprise-grade Retrieval-Augmented Generation (RAG) system for policy, HR, and compliance.
    </p>
    """,
    unsafe_allow_html=True
)

st.divider()

# ======================================================
# SIDEBAR
# ======================================================
with st.sidebar:
    st.markdown("## 🧠 System Overview")

    st.markdown(
        """
        This application demonstrates a **production-style RAG pipeline**:

        - 🔍 **Dense Retrieval** (FAISS)
        - 🎯 **Cross-Encoder Re-Ranking**
        - 🧠 **Grounded LLM Generation**
        - 🧪 **Faithfulness Evaluation**
        - 📊 **Transparent Metrics & Insights**

        Designed for **enterprise policy decision-support**, not just chat.
        """
    )

    st.divider()

    st.markdown("### ⚙️ Display Controls")
    show_sources = st.checkbox("Show Evidence & Citations", True)
    show_metrics = st.checkbox("Show Raw Metrics (JSON)", False)

# ======================================================
# INPUT
# ======================================================
query = st.chat_input("Ask a policy-related question…")

if query:
    with st.spinner("🔎 Retrieving evidence and generating a grounded answer…"):
        data = answer_question(query)

    answer = data["answer"]
    sources = data["sources"]
    metrics = data["metrics"]
    insight = data["insight"]

    # ======================================================
    # TOP KPI / TRUST BAR
    # ======================================================
    st.markdown("### 📊 System Performance Snapshot")

    kpi1, kpi2, kpi3, kpi4 = st.columns(4)
    kpi1.metric("⏱ Retrieval (ms)", metrics["retrieval_time_ms"])
    kpi2.metric("🎯 Re-rank (ms)", metrics["rerank_time_ms"])
    kpi3.metric("🧠 Generation (ms)", metrics["generation_time_ms"])
    kpi4.metric("🧪 Faithfulness", metrics["faithfulness_score"])

    # ------------------------------------------------------
    # TRUST / CONFIDENCE INTERPRETATION
    # ------------------------------------------------------
    st.markdown("### 🔒 Trust & Confidence Assessment")

    if metrics["faithfulness_score"] >= 0.6:
        st.success("🟢 **High Confidence** — The answer is strongly supported by retrieved policy content.")
    elif metrics["faithfulness_score"] >= 0.35:
        st.warning("🟡 **Medium Confidence** — The answer is mostly grounded, but review sources if critical.")
    else:
        st.error("🔴 **Low Confidence** — The answer may not be fully supported. Manual verification recommended.")

    st.divider()

    # ======================================================
    # ANSWER
    # ======================================================
    st.markdown("## 🧠 Answer")
    st.markdown(answer)

    # ======================================================
    # SYSTEM INSIGHTS (LLM-INTERPRETED)
    # ======================================================
    st.markdown("## 🔍 System Insights (LLM-Interpreted)")
    st.markdown(
        """
        The following insights are generated by an LLM that **interprets system metrics**
        to explain reliability, performance, and suitability for decision-making.
        """
    )
    st.markdown(insight)

    # ======================================================
    # EVIDENCE & METRICS
    # ======================================================
    st.divider()
    left, right = st.columns(2)

    if show_sources:
        with left:
            with st.expander("📚 Evidence & Citations", expanded=False):
                st.markdown(
                    """
                    Below are the document segments used to generate this answer.
                    This ensures **traceability and auditability**.
                    """
                )
                st.markdown(sources)

    if show_metrics:
        with right:
            with st.expander("📊 Raw Evaluation Metrics (Debug / Audit)", expanded=False):
                st.json(metrics)
